"""LLM-backed summarization of compacted transcript windows.

Replaces the older heuristic (string-concat of turn prefixes) with a
bulleted memo generated by a cheap sibling model. The memo is written to
preserve the *findings* from earlier tool results — stats, names, totals,
open questions — so the model can continue the investigation coherently
after the raw turns are dropped from the active prompt.

The runtime calls `summarize_for_compaction` inside `compact_if_needed`.
On any failure (API error, timeout, missing summarizer_model) the caller
falls back to the heuristic summary, so compaction never blocks on this.
"""

from __future__ import annotations

import asyncio
import json
import logging

from core.persistence import (
    ToolRunRecord,
    TurnRecord,
)
from core.providers.base import BaseLLMClient
from core.providers.types import Message, MessageResponse, TextEvent
from core.agent.compaction.token_counting import count_text_tokens

logger = logging.getLogger(__name__)


SUMMARIZER_SYSTEM_PROMPT = """You compress the earlier portion of a \
conversation between a user and an NFL statistics agent into a compact \
memo so a future model can continue the investigation coherently.

The agent answers questions about NFL players, teams, and plays by \
running SQL against a local database and other tools. Preserve:
- the user's overall goal in this conversation
- concrete facts uncovered so far (player names, seasons, stats, totals, \
leaderboards — anything the user or the model would need to reference)
- which tools were run and the gist of what they returned
- open questions, pending follow-ups, or things the model said it would \
check next

Omit small talk, retries, and tool input minutiae. Be factual and dense. \
Use short bullets, not prose. Target 200-500 words. Do not invent facts \
that are not in the source turns."""


# Hard budget for the input we feed the summarizer. Well below any
# provider's context window; tool results are truncated if the
# concatenated input would exceed this.
SUMMARIZER_INPUT_BUDGET_TOKENS = 60_000

# Hard wall-clock ceiling for the summarizer call. Haiku/mini latency is
# typically 2-5s; 30s absorbs cold starts without stalling the main loop.
SUMMARIZER_TIMEOUT_SECONDS = 30.0

# Cap per-tool-result length when the total input needs trimming. Keeps
# each dropped tool's "shape" visible to the summarizer even after the
# cut.
TOOL_RESULT_MIN_CHARS_IN_SUMMARY_INPUT = 400
TOOL_RESULT_MAX_CHARS_IN_SUMMARY_INPUT = 4_000


async def summarize_for_compaction(
    client: BaseLLMClient,
    *,
    summarizer_model: str | None,
    source_turns: list[TurnRecord],
    tool_runs_by_turn: dict[str, list[ToolRunRecord]],
) -> str:
    """Produce a compact memo for the given window of turns.

    Raises on failure — the caller decides whether to fall back. Callers
    in this codebase fall back to the heuristic summary.
    """
    input_text = _build_summarizer_input(source_turns, tool_runs_by_turn)
    messages = [Message(role="user", text=input_text)]
    response: MessageResponse = await asyncio.wait_for(
        client.create_message(
            messages=messages,
            system=SUMMARIZER_SYSTEM_PROMPT,
            model=summarizer_model,
        ),
        timeout=SUMMARIZER_TIMEOUT_SECONDS,
    )
    summary = "".join(
        block.text for block in response.content if isinstance(block, TextEvent)
    ).strip()
    if not summary:
        raise RuntimeError("Summarizer returned empty content")
    return summary


def _build_summarizer_input(
    source_turns: list[TurnRecord],
    tool_runs_by_turn: dict[str, list[ToolRunRecord]],
) -> str:
    """Flatten the window of turns into a single text payload.

    Two-pass truncation: first build with a generous per-tool-result cap,
    then if the total exceeds the input budget, rebuild with a tight cap.
    """
    text = _flatten_turns(
        source_turns,
        tool_runs_by_turn,
        tool_result_char_cap=TOOL_RESULT_MAX_CHARS_IN_SUMMARY_INPUT,
    )
    if count_text_tokens(text) <= SUMMARIZER_INPUT_BUDGET_TOKENS:
        return text
    logger.info(
        "summarizer input exceeded budget; retrying with tighter tool-result cap"
    )
    return _flatten_turns(
        source_turns,
        tool_runs_by_turn,
        tool_result_char_cap=TOOL_RESULT_MIN_CHARS_IN_SUMMARY_INPUT,
    )


def _flatten_turns(
    source_turns: list[TurnRecord],
    tool_runs_by_turn: dict[str, list[ToolRunRecord]],
    *,
    tool_result_char_cap: int,
) -> str:
    sections: list[str] = [
        "Earlier turns to summarize (most recent last):",
        "",
    ]
    for turn in source_turns:
        text = (turn.text or "").strip()
        if text:
            sections.append(f"{turn.role.upper()}: {text}")
        for tool_run in tool_runs_by_turn.get(turn.id, []):
            sections.append(_format_tool_run(tool_run, tool_result_char_cap))
        sections.append("")
    return "\n".join(sections).strip()


def _format_tool_run(tool_run: ToolRunRecord, result_char_cap: int) -> str:
    input_json = json.dumps(tool_run.input, sort_keys=True)
    if len(input_json) > 400:
        input_json = input_json[:400] + "…"
    result = (tool_run.result or "").strip()
    if len(result) > result_char_cap:
        result = result[:result_char_cap] + f"\n…[truncated, {len(tool_run.result or '')} chars total]"
    status = tool_run.status
    lines = [f"TOOL {tool_run.tool_name} ({status})", f"  input: {input_json}"]
    if result:
        lines.append(f"  result: {result}")
    if tool_run.error:
        lines.append(f"  error: {tool_run.error}")
    return "\n".join(lines)
