"""Database browser: ad-hoc SQL execution + save-as-Report.

The browser tab runs SELECT/WITH queries through `SQLExecutionService`
(async wrapper over the same sandbox the agent uses) and can convert
any result into a new `kind=table_chat` session so the user can keep
working with it through the agent.

Both methods are thin compositions over existing infrastructure — see
`backend/application/sql_execution.py` for the SQL execution seam and
`backend/application/tables.py` for the table-chat session lifecycle.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

from backend.application.sql_execution import SQLExecutionService
from backend.application.tables import TableChatService
from backend.data import RuntimeStore, SessionRecord
from backend.domain.tools.sandbox.runner import SQLResult
from backend.domain.tools.sandbox.schema import build_schema_response

logger = logging.getLogger(__name__)


@dataclass
class DatabaseService:
    store: RuntimeStore
    table_chat_service: TableChatService
    sql_execution: SQLExecutionService

    def list_browseable_tables(self) -> list[dict]:
        """Project the agent's schema response down to what the picker needs.

        Drops aliases, joins, and the global table count — the UI only needs
        each table's name and its columns (name + type) for the dropdown
        and the auto-generated `SELECT *`.
        """
        payload = build_schema_response()
        tables = []
        for name, info in sorted(payload.get("tables", {}).items()):
            columns = [
                {"name": col["name"], "type": col["type"]}
                for col in info.get("columns", [])
            ]
            tables.append({"name": name, "columns": columns})
        return tables

    async def run_query(self, sql: str) -> SQLResult:
        """Run `sql` through the read-only sandbox via `SQLExecutionService`."""
        return await self.sql_execution.run(sql)

    async def save_sql_as_report(
        self,
        *,
        sql: str,
        title: str | None,
        user_id: int,
    ) -> SessionRecord:
        """Run `sql` server-side, then mint a Report seeded with the result.

        Sandbox runs FIRST so a bad query 400s without leaving an orphan
        session behind. Zero-row results are intentionally allowed — they
        match the post-creation editable-SQL behavior on existing Reports
        (the user can iterate without the agent).
        """
        result = await self.run_query(sql)
        return await self.save_query_as_report(
            sql=sql,
            columns=result.columns,
            rows=result.rows,
            row_count=result.row_count,
            truncated=result.truncated,
            title=title,
            user_id=user_id,
        )

    async def save_query_as_report(
        self,
        *,
        sql: str,
        columns: list[str],
        rows: list[dict],
        row_count: int,
        truncated: bool,
        title: str | None,
        user_id: int,
    ) -> SessionRecord:
        """Mint a `kind=table_chat` session seeded with the rows.

        The user lands in `TableChatView` immediately — the existing
        save-to-CSV flow inside that view handles persisting to the
        Reports library if/when the user is done iterating.
        """
        session = await self.table_chat_service.create_table_chat(
            user_id=user_id,
            title=title,
        )
        await self.store.upsert_table_state(
            session.id,
            columns=list(columns),
            rows=list(rows),
            last_sql=sql,
            row_count=row_count,
            truncated=truncated,
        )
        # Mirror the seed that `create_report` performs (runtime.py) so the
        # agent's first turn knows what's pinned. Without this the transcript
        # is empty and the agent answers "I don't have visibility into any
        # table" when the user asks about the rows above.
        column_list = ", ".join(columns) if columns else "(none)"
        sql_block = f"\n- Generated by this SQL:\n```sql\n{sql}\n```" if sql else ""
        summary_text = (
            "This Report was created from the Database browser. "
            "The current table contains:\n"
            f"- {row_count} rows × {len(columns)} columns\n"
            f"- Columns: {column_list}"
            f"{sql_block}\n\n"
            "If the user asks to refine the table (more rows, different "
            "filters, additional columns), call `set_table` with a new "
            "SQL query — typically a variation of the SQL above. To "
            "answer questions WITHOUT changing the table, use "
            "`execute_sql` or any other research tool. The rows of the "
            "current table are NOT a database table you can query — "
            "they live only in the UI."
        )
        await self.store.seed_summary(session.id, summary_text)
        logger.info(
            "Created table chat %s from database browser (%d rows)",
            session.id,
            row_count,
        )
        return session
